env: 'local'
storage_path: 'C:\Users\sshpi\LearningSprints\API3sprint\internal\storage\storage.db'
http_server:
  address: 'localhost:8080'
  timeout: 4s
  idle_timeout: 60s
  user: 'myuser'
  password: 'mypass'
