env: 'local'
storage_path: 'C:/Users/sshpi/Learning sprints/Learning-sprints/API 3 SPRINT/storage/storage.db'
http_server:
  address: 'localhost:8080'
  timeout: 4s
  idle_timeout: 60s
  user: 'myuser'
  password: 'mypass'
